In [4]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from matplotlib import font_manager, rc

font_location = 'C:/Windows/Fonts/malgun.ttf' # For Windows
font_name = font_manager.FontProperties(fname=font_location).get_name()
rc('font', family=font_name)

In [5]:
raw = pd.read_csv('Data/kospi.csv', encoding = 'cp949')

# 전처리

In [6]:
raw.head()

,일자,현재지수,대비,등락률(%),배당수익률(%),주가이익비율,주가자산비율,시가지수,고가지수,저가지수,거래량(천주),거래대금(백만원),상장시가총액(백만원)
0,2000/01/04,"1,059.04",30.97,3.01,0.63,0.0,0.0,"1,028.33","1,066.18","1,016.59","195,899","3,771,013",NaN
1,2000/01/05,986.31,-72.73,-6.87,0.68,0.0,0.0,"1,006.87","1,047.70",984.05,"257,696","4,798,126",NaN
2,2000/01/06,960.79,-25.52,-2.59,0.70,0.0,0.0,"1,013.95","1,014.90",953.50,"203,524","3,726,898",NaN
3,2000/01/07,948.65,-12.14,-1.26,0.71,0.0,0.0,949.17,970.16,930.84,"215,664","3,696,686",NaN
4,2000/01/10,987.24,38.59,4.07,0.68,0.0,0.0,979.67,994.94,965.02,"240,175","3,815,037",NaN

In [23]:
raw.dtypes

일자              object
현재지수            object
대비             float64
등락률(%)         float64
배당수익률(%)       float64
주가이익비율         float64
주가자산비율         float64
시가지수            object
고가지수            object
저가지수            object
거래량(천주)         object
거래대금(백만원)       object
상장시가총액(백만원)     object
dtype: object

In [24]:
raw['일자'] = raw['일자'].apply(lambda x: x.replace('/','')).astype('int')

In [25]:
raw['현재지수'] = raw['현재지수'].apply(lambda x: x.replace(',','')).astype('float')

In [7]:
raw['등락률(%)'] = raw['현재지수'].pct_change().fillna(0) +1

In [8]:
raw = raw[['일자','현재지수','등락률(%)']]

In [9]:
raw.head()

         일자     현재지수    등락률(%)
0  20000104  1059.04  1.000000
1  20000105   986.31  0.931325
2  20000106   960.79  0.974126
3  20000107   948.65  0.987365
4  20000110   987.24  1.040679

In [10]:
raw['GIJUN_MONTH'] = raw['일자'].apply(lambda x: x//100)

In [11]:
raw.tail()

            일자     현재지수    등락률(%)  GIJUN_MONTH
4587  20180730  2293.51  0.999355       201807
4588  20180731  2295.26  1.000763       201807
4589  20180801  2307.07  1.005145       201808
4590  20180802  2270.20  0.984019       201808
4591  20180803  2287.68  1.007700       201808

# Historical Simulation을 위한 기초 data 생성

In [12]:
column_list = ['GIJUN_MONTH','SILH_SUIK_RT','KOSPI(월초)','KOSPI(월말)']
data = DataFrame(columns = column_list)

# 월초
jisu1_list = []

#월말
jisu2_list = []

month_list = []
suik_list = []

for month in raw['GIJUN_MONTH'].unique():
    temp = raw[raw['GIJUN_MONTH'] == month]
    
    # 2018년 8월 자료는 제외
    if month == 201808: continue
    
    # 월 기록
    month_list.append(month)
    
    # 월초 주가 기록
    jisu1_list.append(temp['현재지수'].iloc[0])
    
    # 월말 주가 기록
    jisu2_list.append(temp['현재지수'].iloc[-1])
    
    # 월 수익률 기록
    suik_list.append(np.prod(temp['등락률(%)']))
    
    
    
data['GIJUN_MONTH'] = month_list
data['SILH_SUIK_RT'] = suik_list
data['KOSPI(월초)'] = jisu1_list
data['KOSPI(월말)'] = jisu2_list

In [13]:
data

     GIJUN_MONTH  SILH_SUIK_RT  KOSPI(월초)  KOSPI(월말)
0         200001      0.891260    1059.04     943.88
1         200002      0.877633     928.75     828.38
2         200003      1.039306     894.66     860.94
3         200004      0.842556     846.44     725.39
4         200005      1.008947     752.59     731.88
5         200006      1.122069     738.49     821.22
6         200007      0.859660     835.21     705.97
7         200008      0.975424     727.10     688.62
8         200009      0.890506     692.19     613.22
9         200010      0.838981     589.22     514.48
10        200011      0.989796     548.76     509.23
11        200012      0.990947     514.46     504.62
12        200101      1.224506     520.95     617.91
13        200102      0.935573     612.30     578.10
14        200103      0.905068     559.44     523.22
15        200104      1.103475     515.20     577.36
16        200105      1.060274     583.70     612.16
17        200106      0.972180     607.07     595.13
18        200107      0.909969     596.74     541.55
19        200108      1.006574     562.79     545.11
20        200109      0.879969     541.83     479.68
21        200110      1.121185     500.64     537.81
22        200111      1.197244     544.09     643.89
23        200112      1.077358     650.66     693.70
24        200201      1.078377     724.95     748.07
25        200202      1.096141     742.42     819.99
26        200203      1.092184     834.21     895.58
27        200204      0.940552     875.83     842.34
28        200205      0.945461     859.86     796.40
29        200206      0.932597     804.93     742.72
..           ...           ...        ...        ...
193       201602      1.002406    1924.82    1916.66
194       201603      1.041317    1947.42    1995.85
195       201604      0.999148    1973.57    1994.15
196       201605      0.994609    1978.15    1983.40
197       201606      0.993420    1982.72    1970.35
198       201607      1.023265    1987.32    2016.19
199       201608      1.009156    2029.61    2034.65
200       201609      1.004414    2032.72    2043.63
201       201610      0.982658    2054.86    2008.19
202       201611      0.987695    2007.39    1983.48
203       201612      1.021669    1983.75    2026.46
204       201701      1.020287    2026.16    2067.57
205       201702      1.011642    2080.48    2091.64
206       201703      1.032792    2102.65    2160.23
207       201704      1.020928    2167.51    2205.44
208       201705      1.064359    2219.67    2347.38
209       201706      1.018919    2344.61    2391.79
210       201707      1.004566    2394.48    2402.71
211       201708      0.983552    2422.96    2363.19
212       201709      1.013236    2357.69    2394.47
213       201710      1.053857    2433.81    2523.43
214       201711      0.981351    2556.47    2476.37
215       201712      0.996414    2475.41    2467.49
216       201801      1.040110    2479.65    2566.46
217       201802      0.945801    2568.54    2427.36
218       201803      1.007617    2402.16    2445.85
219       201804      1.028428    2444.16    2515.38
220       201805      0.963278    2505.61    2423.01
221       201806      0.960017    2438.96    2326.13
222       201807      0.986729    2271.54    2295.26

[223 rows x 4 columns]

In [14]:
data.to_csv('RAW_DATA.csv')

# 시뮬레이션 시작

In [16]:
def find_true_r(temp_list):
    
    # 방정식을 풀어 얻은 해 중, 1에 가장 가까운 값을 갖는 것을 사용한다.
    test_list = [np.abs(r-1) for r in temp_list]
    
    return temp_list[np.argmin(test_list)]

In [18]:
from collections import OrderedDict
from sympy import Symbol, solve

n_period = 12

investment = 10000
total_investment = n_period * investment

rf_annual = 0.03
rf_monthly = np.power(1+rf_annual, 1/12) -1



store_dict = OrderedDict(\
                         {'기준 월' : [],
                          'KOSPI_0' : [],
                          'KOSPI_T' : [],
                          
                          '전체 시나리오' : [],
                          '메인 시나리오' : [],
                          '세부 시나리오' : [],
                          
                          'LS 수익률(%)' : [],
                          'BH 수익률(%)' : [],
                          'DCA1 수익률(%)' : [],
                          'DCA1* 수익률(%)' : [],
                          'DCA2 수익률(%)' : [],
                          
                          'P_0' : [],
                          'P_T' : [],
                          'H_DCA1' : [],
                          'H_DCA1*' : [],
                          'H_DCA2' : [],
                          
                          })
for i in range(1):
#for i in range(len(data)):
    
    
    if i % 50 == 0 :
        print(i)
    
    
    temp = data.iloc[i:i+n_period]
    
    # full year가 아니면 제외
    if not len(temp) == n_period:
        continue
    
    #기준 월 기록
    gijun_month = temp['GIJUN_MONTH'].iloc[0]
    store_dict['기준 월'].append(gijun_month)
    
    # 최초시점 KOSPI 기록
    kospi_0 = temp['KOSPI(월초)'].iloc[0]
    store_dict['KOSPI_0'].append(kospi_0)
    
    # 중간시점 KOSPI 기록
    kospi_05 = temp['KOSPI(월말)'].iloc[n_period//2]
    
    
    # 마지막 시점 KOSPI 기록
    kospi_t = temp['KOSPI(월말)'].iloc[-1]
    store_dict['KOSPI_T'].append(kospi_t)
    
    # state : 각각의 시나리오 (ex: 상상)를 기록할 변수
    total_senario = ''
    main_senario = ''
    sebu_senario = '' 

    ################ total_senario 계산 ##################
    for index in temp.index:
        row = temp.loc[index, :]
        
        # kospi_new : 해당 기의 마지막 날 주가
        kospi_new = row['KOSPI(월말)']
           
        # t기간 수익률
        suik_t = kospi_new / kospi_0 
        
        ##### 상, 하 state 기록
        if suik_t >= 1:
            total_senario += '상'
        else:
            total_senario += '하'
    
    # total senario = xxxxxxxxxxxx (x : n_period)
    store_dict['전체 시나리오'].append(total_senario)
    
    ######################## 메인 시나리오 계산 ###########################
    
    up = 0
    down = 0
    
    for letter in total_senario:
        if letter == '상':
            up += 1
        elif letter == '하':
            down += 1
    
    # 메인 시나리오 계산
    # up이 절반 이상이면
    if up > n_period/2 :
        main_senario += '강'
    
    elif down > n_period/2 :
        main_senario += '약'
    
    elif up == n_period/2 :
        if kospi_t >= kospi_0:
            main_senario += '강'
            
        elif kospi_t < kospi_0:
            main_senario += '약'
            
    
    store_dict['메인 시나리오'].append(main_senario)
    
    
    
    ############################ 세부 시나리오 계산 ############################
    # 전기 (최초 n_period/2 개월) 
    up = 0
    down = 0
    
    for letter in total_senario[:n_period//2]:
        if letter == '상':
            up += 1
        elif letter == '하':
            down += 1          
    
    if up > n_period/4 :
        sebu_senario += '강'
        
    if down > n_period/4 :
        sebu_senario += '약'
        
    if up == n_period/4 :
        if kospi_05 >= kospi_0:
            sebu_senario += '강'
        
        elif kospi_05 < kospi_0:
            sebu_senario += '약'
        
    # 후기
    up = 0
    down = 0
    
    for letter in total_senario[n_period//2:]:
        if letter == '상':
            up += 1
        elif letter == '하':
            down += 1          
    
    if up > n_period/4 :
        sebu_senario += '강'
        
    if down > n_period/4 :
        sebu_senario += '약'
        
    if up == n_period/4 :
        if kospi_t >= kospi_05:
            sebu_senario += '강'
        elif kospi_t < kospi_05:
            sebu_senario += '약'
        
        
    store_dict['세부 시나리오'].append(sebu_senario)
    
    
    
    ################### P_0 , P_T 계산 ###############################
    P_0 = temp['KOSPI(월초)'].iloc[0]
    P_T = temp['KOSPI(월말)'].iloc[-1]    
    
    P_T_0 = P_T / P_0
    
    ###################### LS , BH 수익률 계산 ###################
    LS_HPR = P_T / P_0 -1  # HPR  0.xx 
    LS_annual = np.power(LS_HPR +1 , 12/n_period) -1 # annual 0.xxx
    
    BH_HPR = (total_investment/2 * (P_T/P_0) + 
              total_investment/2 * np.power( 1+ rf_annual, 12/ n_period)) / total_investment -1
    
    
    BH_annual = np.power(BH_HPR +1, 12/n_period) -1
    
    store_dict['LS 수익률(%)'].append(round(LS_annual * 100,3))
    store_dict['BH 수익률(%)'].append(round(BH_annual * 100,3))
    
    
    
    
    ##################### DCA1 FV 계산 ########################
    FV_sum = 0
    
    for i in range(n_period):
        FV_sum += investment * np.prod(temp['SILH_SUIK_RT'].iloc[i:])
        
    # FV_sum : 적립식 투자안의 미래가치의 총합
    FV_sum = np.round(FV_sum,2)
    
    #################### DCA1 수익률 계산 ########################
    DCA1_HPR = FV_sum / total_investment -1 # HPR 0.xxx
    DCA1_annual = np.power(DCA1_HPR +1, 12 / n_period) -1  # annual 0.xxx
    DCA1_monthly = np.power(DCA1_annual +1, 1/n_period) -1
    
    store_dict['DCA1 수익률(%)'].append(round(DCA1_annual * 100 , 3))

    
    
    
    ################### DCA1* 수익률 계산 ##########################
    irr_path = np.ones(n_period+1) * -investment
    irr_path[-1] += (FV_sum + investment)
    
    # DCA1_star : 월별 수익률
    # IRR_annual : 연환산 수익률
    DCA1_star_monthly = np.irr(irr_path)    # monthly 0. xxxx
    DCA1_star_HPR = np.power(DCA1_star_monthly +1 ,n_period) -1
    DCA1_star_annual = np.power(DCA1_star_monthly +1, 12) -1 # annual 0. xxx
    
    store_dict['DCA1* 수익률(%)'].append(np.round(DCA1_star_annual * 100,3))

    
    
    
    ####################### DCA2 FV 계산 ##########################
    DCA2_FV = 0
    
    for i in range(n_period):
        DCA2_FV += investment * np.power(1+rf_monthly, i) * np.prod(temp['SILH_SUIK_RT'].iloc[i:])
    
    DCA2_FV = round(DCA2_FV, 2)
    
    ####################### DCA2 수익률 계산 ##########################
    DCA2_HPR = DCA2_FV/ total_investment -1
    DCA2_annual = np.power(DCA2_HPR +1, 12/ n_period) -1
    
    store_dict['DCA2 수익률(%)'].append(round(DCA2_annual * 100,3))
    
    
    
    
    ####################### DCA2 * 수익률 계산 #############################
    '''
    r = Symbol('r')
    equation = 0
    
    for i in range(n_period):
        equation += round(np.prod(temp['SILH_SUIK_RT'].iloc[i:]),5) * (r ** i)
    equation -= n_period * r ** n_period
    result_list = solve(equation)
    
    DCA2_star_monthly = find_true_r(result_list) -1
    DCA2_star_annual = np.power(DCA2_star_monthly +1 , 12) -1
    DCA2_star_HPR = np.power(DCA2_star_monthly +1 , n_period) -1
    
    store_dict['DCA2* 수익률(%)'].append(round(DCA2_star_annual * 100,3))
    ''' 
    
    
    
    
    
    
    # H_DCA1 = P_T / (1 + DCA1_HPR)
    # H_DCA1* = P_T / (1 + DCA1*_HPR)
    
    H_DCA1 = P_T / (1 + DCA1_HPR)
    H_DCA1_star = round(P_T / (1+ DCA1_star_HPR),5)
    
    H_DCA2 = P_T / (1 + DCA2_HPR)
    H_DCA2_star = round(P_T / (1+DCA2_star_HPR), 5)
    
    store_dict['P_0'].append(1)
    store_dict['P_T'].append(P_T/ P_0)
    
    store_dict['H_DCA1'].append(H_DCA1/P_0)
    store_dict['H_DCA1*'].append(H_DCA1_star/P_0)
    
    store_dict['H_DCA2'].append(H_DCA2/P_0)
    #store_dict['H_DCA2*'].append(H_DCA2_star/P_0)
    
    
    
# df 결과 값 저장 : DataFrame    
df_DCA = DataFrame(store_dict)

#df_DCA.T.to_csv('모든 시나리오 %s개월.csv'%n_period)

0

In [19]:
df_DCA.head()

,기준 월,KOSPI_0,KOSPI_T,전체 시나리오,메인 시나리오,세부 시나리오,LS 수익률(%),BH 수익률(%),DCA1 수익률(%),DCA1* 수익률(%),DCA2 수익률(%),P_0,P_T,H_DCA1,H_DCA1*,H_DCA2
0,200001,1059.04,504.62,하하하하하하하하하하하하,약,약약,-52.351,-24.676,-29.598,-49.512,-28.511,1,0.476488,0.676807,0.943766,0.666519

In [53]:
df_DCA.T

,0,1,2,3,4,5,6,7,8,9,...,418,419,420,421,422,423,424,425,426,427
기준 월,198001,198002,198003,198004,198005,198006,198007,198008,198009,198010,...,201411,201412,201501,201502,201503,201504,201505,201506,201507,201508
KOSPI_0,100,104.48,103.96,105.43,116.54,116.77,112.05,112.28,112.55,109.85,...,1952.97,1965.22,1926.44,1952.68,1996.81,2028.45,2132.23,2102.37,2097.89,2008.49
KOSPI_T,128.99,118.27,123.5,119.8,131.44,125.76,122.44,125.04,118.82,117.71,...,2523.43,2476.37,2467.49,2566.46,2427.36,2445.85,2515.38,2423.01,2326.13,2295.26
전체 시나리오,상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상,하상상상상상상상상상상상하상상상상상상상상상상상상상상상상상상상상상상상,상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상,상상상상상상상상상상하상상상상상상상상상상상상상상상상상상상상상상상상상,하하하하하하하하하하하상상상상상상상상상상상상상하상상상상상상상상상상상,하하하하하하하하하하상상상상상상상상상상상상상하상상상상상상상상상상상상,상상하하하하하하하상상상상상상상상상상상상상상상상상상상상상상상상상상상,상하하하하하하하상상상상상상상상상상상상상상상상상상상상상상상상상상상상,하하하하하하하상상상상상상상상상상상상상상상상상상상상상상상상상상상상상,하하하하하하상상상상상상상상상상상상상상상상상상상상상상상상상상상상상상,...,상하하상상상상상상하상상상상하하상상상상상상상상상상상상상상상상상상상상,하하상상상상상상하하상상하하하상상상상상상상상상상상상상상상상상상상상상,상상상상상상상상상상상상하하상상상상상상상상상상상상상상상상상상상상상상,상상상상상상하상상상상하하상상상상상상상상상상상상상상상상상상상상상상상,상상상상상하하상하하하하하하하하상상상상하상상상상상상상상상상상상상상상,상상상상하하상하하하하하하하하하상상하하하상상상상상상상상상상상상상상상,하하하하하하하하하하하하하하하하하하하하하하상상상상상상상상상상상상상상,하하하하하하하하하하하하하하하하하하하하하상상상상상상상상상상상상상상상,하하하하하하하하하하하하하하하하하하하하상상상상상상상상상상상상상상상상,하하상하하하하하하하하상상상하하상상상상상상상상상상상상상상상상상상상상
메인 시나리오,강,강,강,강,강,강,강,강,강,강,...,강,강,강,강,강,강,약,약,약,강
세부 시나리오,강강,강강,강강,강강,약강,약강,강강,강강,강강,강강,...,강강,강강,강강,강강,약강,약강,약강,약강,약강,약강
LS 수익률(%),8.856,4.219,5.909,4.351,4.092,2.503,3,3.653,1.823,2.33,...,8.918,8.011,8.601,9.539,6.725,6.436,5.663,4.845,3.502,4.549
BH 수익률(%),4.766,2.311,3.195,2.38,2.245,1.428,1.682,2.018,1.082,1.34,...,4.799,4.311,4.628,5.136,3.626,3.473,3.065,2.637,1.94,2.483
DCA1 수익률(%),2.998,-0.185,1.155,-0.036,2.967,1.348,0.376,1.001,-0.8,-1.161,...,7.047,6.148,5.815,6.97,4.749,4.826,5.641,4.182,2.652,2.089
DCA1* 수익률(%),5.834,-0.359,2.248,-0.07,5.773,2.623,0.733,1.948,-1.556,-2.259,...,13.713,11.964,11.316,13.563,9.241,9.391,10.977,8.138,5.16,4.066
DCA2 수익률(%),4.447,1.223,2.587,1.384,4.436,2.792,1.807,2.443,0.618,0.256,...,8.568,7.65,7.308,8.475,6.218,6.293,7.116,5.63,4.074,3.502
DCA2* 수익률(%),5.799,-0.348,2.21,-0.069,5.815,2.599,0.719,1.927,-1.516,-2.2,...,14.281,12.303,11.56,13.972,9.3,9.439,11.085,8.079,5.041,3.948
P_0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
P_T,1.2899,1.13199,1.18796,1.1363,1.12785,1.07699,1.09273,1.11364,1.05571,1.07155,...,1.2921,1.2601,1.28085,1.31433,1.21562,1.20577,1.17969,1.15251,1.1088,1.14278
H_DCA1,1.18051,1.13828,1.14772,1.13753,1.03314,1.03459,1.08048,1.08085,1.08145,1.10976,...,1.05335,1.05358,1.08107,1.07379,1.05766,1.04679,1.00063,1.01922,1.02507,1.07404
H_DCA1*,1.08813,1.14428,1.11132,1.1387,0.953065,0.996499,1.06906,1.05101,1.10657,1.14759,...,0.87876,0.897778,0.928586,0.897425,0.932472,0.921132,0.863119,0.911408,0.953449,1.01401
H_DCA2,1.13207,1.09145,1.10032,1.0904,0.990155,0.991597,1.03558,1.03586,1.03637,1.06336,...,1.0097,1.01009,1.0366,1.02971,1.01438,1.00404,0.95987,0.977888,0.983622,1.03067
H_DCA2*,1.08922,1.14388,1.11255,1.13865,0.951948,0.997208,1.06948,1.05166,1.10522,1.14549,...,0.865723,0.889669,0.922507,0.887782,0.930967,0.919913,0.860597,0.912909,0.956708,1.01745

# 세부 시나리오

In [54]:
def summarize_by_senario(df, Total = True, **kwargs):
    main_senario_list = ['강', '보', '약']

    column_list = ['메인 시나리오', '세부 시나리오', 'N', 
                   'P_0', 'P_T','H_DCA1', 'H_DCA1*', 'H_DCA2', 'H_DCA2*',
                   
                   'DCA1 > LS', 'DCA1 > BH', 'DCA2 > LS', 'DCA2 > BH',
                   'DCA1* > LS', 'DCA1* > BH', 'DCA2* > LS', 'DCA2* > BH',

                   'H_DCA1 < P_T', 'H_DCA1* < P_T',
                   'H_DCA2 < P_T', 'H_DCA2* < P_T',

                   'LS 수익률(%)','BH 수익률(%)', 'DCA1 수익률(%)' , 'DCA1* 수익률(%)', 'DCA2 수익률(%)' , 'DCA2* 수익률(%)', 
                   'LS 표준편차(%)', 'BH 표준편차(%)', 'DCA1 표준편차(%)', 'DCA1* 표준편차(%)' ,'DCA2 표준편차(%)', 'DCA2* 표준편차(%)']

    store_dict = OrderedDict(\
                             dict((key , []) for key in column_list))

    # 결과 저장 DataFrame

    # 시나리오 기록
    
    if Total == True :
        store_dict['메인 시나리오'].append('전체')
        store_dict['세부 시나리오'].append('전체')
    
    elif Total == False:
        store_dict['메인 시나리오'].append(kwargs['main'])
        store_dict['세부 시나리오'].append(kwargs['sebu'])
    

    # N
    store_dict['N'].append(len(df))



    ################### # P_0 ,P_T , H_DCA1 , H_DCA1 ########################
    for column in ['P_0', 'P_T' , 'H_DCA1', 'H_DCA1*', 'H_DCA2', 'H_DCA2*']:
        store_dict[column].append(df[column].mean())



    ################# [DCA 1*. DCA 2*] > [LS수익률(%), BH수익률(%)]######################
    for column in ['DCA1','DCA1*', 'DCA2', 'DCA2*']:
        suik_column = column + ' 수익률(%)'

        DCA_win_LS_rate = np.sum(df['%s'%suik_column] > df['LS 수익률(%)']) / len(df)
        DCA_win_BH_rate = np.sum(df['%s'%suik_column] > df['BH 수익률(%)']) / len(df)

        store_dict['%s > LS'%column].append(DCA_win_LS_rate)
        store_dict['%s > BH'%column].append(DCA_win_BH_rate)




    ############### DCA1 , DCA1*, DCA2, DCA2*   > 0 (수익이 난 비율) #######################
    store_dict['H_DCA1 < P_T'].append(np.sum(df['H_DCA1'] < df['P_T']) / len(df))
    store_dict['H_DCA1* < P_T'].append( np.sum(df['H_DCA1*'] < df['P_T']) / len(df))

    store_dict['H_DCA2 < P_T'].append(np.sum(df['H_DCA2'] < df['P_T']) / len(df))
    store_dict['H_DCA2* < P_T'].append( np.sum(df['H_DCA2*'] < df['P_T']) / len(df))



    #################### # LS, DCA , DCA1 수익률 기록 #######################################

    for column in ['LS', 'BH', 'DCA1', 'DCA1*', 'DCA2', 'DCA2*']:
        suik_column = column + ' 수익률(%)'
        store_dict[suik_column].append(df[suik_column].mean())

        std_column = column + ' 표준편차(%)'
        store_dict[std_column].append(df[suik_column].std())
                                                                                
    
    return_df = DataFrame(store_dict)
    return return_df

In [55]:
summarize_by_senario(df_DCA, Total=True)

,메인 시나리오,세부 시나리오,N,P_0,P_T,H_DCA1,H_DCA1*,H_DCA2,H_DCA2*,DCA1 > LS,...,DCA1 수익률(%),DCA1* 수익률(%),DCA2 수익률(%),DCA2* 수익률(%),LS 표준편차(%),BH 표준편차(%),DCA1 표준편차(%),DCA1* 표준편차(%),DCA2 표준편차(%),DCA2* 표준편차(%)
0,전체,전체,428,1.0,1.463603,1.138155,1.0217,1.092691,1.008762,0.315421,...,5.696671,11.089472,7.163675,11.686002,19.455952,11.32582,11.273541,21.941555,11.310995,22.415714

In [56]:
from collections import OrderedDict

# 전체 요약
summary_df = summarize_by_senario(df_DCA)

    
# 세부 시나리오별 요약
for main_senario in ['강','보','약']:
    temp = df_DCA[df_DCA['메인 시나리오'] == main_senario]
    
    # 강 보 합, 메인 시나리오 결과 총합
    main_summary_df = summarize_by_senario(temp, Total = False, main = main_senario, sebu = '전체')
    summary_df = pd.concat([summary_df, main_summary_df], axis=0, copy = False)
    sebu_senario_list = sorted(temp['세부 시나리오'].unique())

    for sebu_senario in sebu_senario_list:
        temp2 = temp[temp['세부 시나리오'] == sebu_senario]
        
        sebu_summary_df = summarize_by_senario(temp2, Total=False, main = main_senario, sebu = sebu_senario)
        summary_df = pd.concat([summary_df , sebu_summary_df], axis=0, copy = False)


summary_df.set_index('메인 시나리오', inplace= True)

#df_1.iloc[:,1:] = df_1.iloc[:,1:].apply(lambda x: np.round(x,3))

In [57]:
summary_df.T

메인 시나리오,전체,강,강,강,강,강,강,보,보,보,보,약,약,약,약,약,약
세부 시나리오,전체,전체,강강,강보,강약,보강,약강,전체,강약,보보,약강,전체,강약,보약,약강,약보,약약
N,428,288,233,6,8,13,28,4,1,1,2,136,6,3,23,5,99
P_0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
P_T,1.4636,1.73774,1.85115,1.11314,1.01296,1.44417,1.27128,1.2029,0.944531,0.996899,1.43509,0.890742,0.87319,0.922517,1.16413,1.1745,0.812997
H_DCA1,1.13815,1.28494,1.33704,1.06063,1.07319,1.10293,1.0444,0.999101,1.03753,1.00032,0.979276,0.831414,0.917625,0.939511,0.898221,0.888705,0.804499
H_DCA1*,1.0217,1.09912,1.12977,1.01902,1.19579,0.968666,0.894212,0.891819,1.13707,1.00358,0.71331,0.861562,1.00333,0.963916,0.727889,0.729196,0.887609
H_DCA2,1.09269,1.23495,1.28556,1.0138,1.02514,1.05932,1.00269,0.95725,0.99027,0.957886,0.940423,0.795423,0.876085,0.898294,0.862553,0.8524,0.768944
H_DCA2*,1.00876,1.09212,1.12412,1.01325,1.16467,0.949356,0.888328,0.882855,1.14585,1.00356,0.691007,0.835935,0.989001,0.964014,0.721591,0.709295,0.855738
DCA1 > LS,0.315421,0.0138889,0.00429185,0,0,0,0.107143,0.25,0,0,0.5,0.955882,1,1,0.782609,1,0.989899
DCA1 > BH,0.46028,0.319444,0.236052,0.5,0.125,0.692308,0.857143,0.5,0,0,1,0.757353,0.5,0.333333,1,0.8,0.727273
DCA2 > LS,0.432243,0.15625,0.0901288,0.166667,0.25,0.307692,0.607143,1,1,1,1,1,1,1,1,1,1
DCA2 > BH,0.61215,0.5,0.424893,0.833333,0.375,0.846154,0.928571,0.75,0,1,1,0.845588,0.5,1,1,1,0.818182
DCA1* > LS,0.514019,0.375,0.300429,0.5,0.125,0.692308,0.892857,0.5,0,0,1,0.808824,0.5,0.666667,1,0.8,0.787879
DCA1* > BH,0.654206,0.635417,0.596567,0.833333,0.375,0.769231,0.928571,0.5,0,0,1,0.698529,0.333333,0.666667,1,0.8,0.646465
DCA2* > LS,0.521028,0.385417,0.309013,0.5,0.25,0.692308,0.892857,0.5,0,0,1,0.808824,0.5,0.666667,1,0.8,0.787879
DCA2* > BH,0.642523,0.621528,0.579399,0.833333,0.375,0.769231,0.928571,0.5,0,0,1,0.691176,0.333333,0.666667,1,0.8,0.636364
H_DCA1 < P_T,0.742991,0.791667,0.785408,0.833333,0.375,0.846154,0.928571,0.5,0,0,1,0.647059,0.333333,0.666667,1,0.8,0.575758
H_DCA1* < P_T,0.742991,0.791667,0.785408,0.833333,0.375,0.846154,0.928571,0.5,0,0,1,0.647059,0.333333,0.666667,1,0.8,0.575758
H_DCA2 < P_T,0.808411,0.857639,0.866953,0.833333,0.375,0.846154,0.928571,0.75,0,1,1,0.705882,0.333333,0.666667,1,1,0.646465
H_DCA2* < P_T,0.742991,0.791667,0.785408,0.833333,0.375,0.846154,0.928571,0.5,0,0,1,0.647059,0.333333,0.666667,1,0.8,0.575758
LS 수익률(%),9.94926,16.9698,19.3114,3.61767,-0.146125,10.8518,8.07646,5.814,-1.884,-0.103,12.6215,-4.79623,-4.72083,-2.73767,5.03217,5.177,-7.65024
BH 수익률(%),6.07124,9.87011,11.2609,2.00467,0.2345,6.27069,4.40657,3.2715,-0.765,0.113,6.869,-1.89107,-2.05583,-1.15833,2.7743,2.8864,-3.22845
DCA1 수익률(%),5.69667,7.71109,8.39121,1.63317,-2.50125,7.14485,6.53468,5.8985,-3.082,-0.114,13.395,1.4249,-1.89117,-0.668333,9.08609,9.6002,-0.503455
DCA1* 수익률(%),11.0895,15.0093,16.3335,3.178,-4.86612,13.9067,12.7156,11.4778,-5.997,-0.222,26.065,2.77732,-3.6795,-1.30033,17.6808,18.682,-0.973485
DCA2 수익률(%),7.16368,9.15738,9.83149,3.17367,-1.00012,8.59762,7.99207,7.412,-1.564,1.34,14.936,2.9344,-0.363667,0.828667,10.5652,11.1326,1.01124
DCA2* 수익률(%),11.686,15.3777,16.675,3.40483,-3.89375,14.59,13.0203,12.0927,-6.237,-0.222,27.415,3.85629,-3.06317,-1.27867,18.1785,20.703,0.25303
LS 표준편차(%),19.456,19.0349,19.9559,1.56982,8.09929,15.7262,5.32399,8.68493,NaN,NaN,6.27133,10.0317,5.84093,3.53789,4.24235,6.53525,9.73376
BH 표준편차(%),11.3258,11.6743,12.3122,0.808415,4.0749,9.29447,2.86221,4.62912,NaN,NaN,3.48321,4.54112,2.82411,1.69785,2.22341,3.51345,4.26971
DCA1 표준편차(%),11.2735,11.6102,12.2521,2.32292,7.12959,11.607,4.92297,9.02685,NaN,NaN,3.90606,9.30417,6.52959,3.29804,4.78417,8.9799,9.30998
DCA1* 표준편차(%),21.9416,22.6025,23.8526,4.52007,13.8726,22.5942,9.57937,17.5652,NaN,NaN,7.6014,18.095,12.7055,6.41745,9.30991,17.4767,18.1036
DCA2 표준편차(%),11.311,11.6451,12.2884,2.34014,7.25881,11.6665,4.97602,9.05303,NaN,NaN,3.9004,9.38353,6.63438,3.31572,4.84324,9.10251,9.40975
DCA2* 표준편차(%),22.4157,22.9718,24.2657,4.78763,14.6159,22.7212,9.91092,18.4345,NaN,NaN,7.89414,19.21,13.4793,6.62005,10.29,21.2012,19.4059

In [58]:
summary_df.T.to_csv('시나리오별 통계_%s개월.csv'%n_period)